ASCII Serial Com: ascii_serial_com_register_pointers.h File Reference
ascii_serial_com_register_pointers.h File Reference
ASCII Serial Com Register Pointers.
#include "ascii_serial_com.h"
Classes
struct ascii_serial_com_register_pointers_struct
ASCII Serial Com Register Pointers State struct.
Macros
#define REGWIDTHBITS 8
#define REGWIDTHBYTES 1
#define REGTYPE uint8_t
#define REGPRINTTYPEINT PRIu8
#define REGPRINTTYPEHEX PRIX8
#define _extraInputBuffer_size_ 64
#define DECLARE_ASC_DEVICE_W_REGISTER_POINTERS()
Declarations for ascii_serial_com_device and ascii_serial_com_register_pointers.
#define SETUP_ASC_DEVICE_W_REGISTER_POINTERS(register_map, register_write_masks, nRegs)
Setup for ascii_serial_com_device and ascii_serial_com_register_pointers.
#define _serial_tx_buf_is_empty(usart) ((USART_ISR(usart) & USART_ISR_TXE))
#define _ATOMIC CM_ATOMIC_BLOCK()
#define HANDLE_ASC_COMM_IN_POLLING_LOOP(usart)
Polling for ascii_serial_com_device and ascii_serial_com_register_pointers.
#define READY_TO_STREAM_ASC_DEVICE_W_REGISTER_POINTERS
Check if you should stream a message to the host.
#define STREAM_TO_HOST_ASC_DEVICE_W_REGISTER_POINTERS(data, data_size)
Stream data to the host.
Typedefs
typedef struct ascii_serial_com_register_pointers_struct ascii_serial_com_register_pointers
ASCII Serial Com Register Pointers State struct.
Functions
void ascii_serial_com_register_pointers_init (ascii_serial_com_register_pointers *register_pointers_state, volatile REGTYPE **pointers, REGTYPE *write_masks, uint16_t n_regs)
ASCII Serial Com Register Pointers init.
void ascii_serial_com_register_pointers_handle_message (ascii_serial_com *asc, char ascVersion, char appVersion, char command, char *data, size_t dataLen, void *register_pointers_state)
ASCII Serial Com Register Pointers handle message.
Detailed Description
ASCII Serial Com Register Pointers.
Register interface for devices.
This interface contains an array of pointers, so that each message address points to an arbitrary address. Additionally, a write mask controls which bits of the pointed to words are writable.
You probably want to create the array of pointers like:
 #define NREGS 6
 REGTYPE * reg_pointers[NREGS] = {
  &x,
  &y,
  &z,
  NULL,
  NULL,
  NULL
 };
 REGTYPE reg_write_masks[NREGS] = {
  0,
  0x3,
  0xFF,
  0,
  0,
  0
 }
 ascii_serial_com_register_pointers_init(&rps,reg_pointers,reg_write_masks,NREGS);
Convenience Macros
A set of convenience macros are provided to ease the common use of ascii_serial_com_register_pointers with ascii_serial_com_device.
Required Macros
To use the macros:
Declare the register pointer and register write mask array as above
Before the main() function, put DECLARE_ASC_DEVICE_W_REGISTER_POINTERS() on a line with no semicolon
In the setup portion of main(), before the polling loop, inside a Try/Catch block, put: SETUP_ASC_DEVICE_W_REGISTER_POINTERS(reg_map,reg_write_masks, NREGS);, where the variables are declared as in the previous section.
Inside the polling loop and a Try/Catch block, put: HANDLE_ASC_COMM_IN_POLLING_LOOP(USART1);, replacing USART1 with the appropriate USART.
Number 4 assumes something is putting received bytes into a circular_buffer_uint8 called extraInputBuffer (declared and setup by the macros). This can be accomplished using, for STM32, def_usart_isr_push_rx_to_circ_buf(<usart_isr>,<usart>,&extraInputBuffer) (no semicolon)
Streaming
The boolean valued macro READY_TO_STREAM_ASC_DEVICE_W_REGISTER_POINTERS should be checked before actually streaming a message. and STREAM_TO_HOST_ASC_DEVICE_W_REGISTER_POINTERS(data,data_len); should be run to send the message.
The macros define a bool streaming_is_on that is initialized to false, set to true when a "n" message is received, and set to false when a "f" message is received. It should be used to decide when to start auxiliary routines that prepare to stream messages.
Definition in file ascii_serial_com_register_pointers.h.
Macro Definition Documentation
_ATOMIC
#define _ATOMIC CM_ATOMIC_BLOCK()
Definition at line 254 of file ascii_serial_com_register_pointers.h.
_extraInputBuffer_size_
#define _extraInputBuffer_size_ 64
Definition at line 149 of file ascii_serial_com_register_pointers.h.
_serial_tx_buf_is_empty
#define _serial_tx_buf_is_empty (usart) ((USART_ISR(usart) & USART_ISR_TXE))
Definition at line 233 of file ascii_serial_com_register_pointers.h.
DECLARE_ASC_DEVICE_W_REGISTER_POINTERS
#define DECLARE_ASC_DEVICE_W_REGISTER_POINTERS ()
Value:
  void _handle_nf_messages(ascii_serial_com *asc, char ascVersion,             \
                           char appVersion, char command, char *data,          \
                           size_t dataLen, void *state_vp);                    \
  bool streaming_is_on = false;                                                \
  circular_buffer_uint8 extraInputBuffer;                                      \
                                                                               \
  uint8_t _tmp_byte;                                                           \
  uint8_t _extraInputBuffer_raw[_extraInputBuffer_size_];                      \
  ascii_serial_com_device _ascd;                                               \
  ascii_serial_com_register_pointers _reg_pointers_state;                      \
  ascii_serial_com_device_config _ascd_config = {                              \
      .func_rw = ascii_serial_com_register_pointers_handle_message,            \
      .state_rw = &_reg_pointers_state,                                        \
      .func_nf = _handle_nf_messages,                                          \
      .state_nf = &streaming_is_on};                                           \
  void _handle_nf_messages(__attribute__((unused)) ascii_serial_com *asc,      \
                           __attribute__((unused)) char ascVersion,            \
                           __attribute__((unused)) char appVersion,            \
                           char command, __attribute__((unused)) char *data,   \
                           __attribute__((unused)) size_t dataLen,             \
                           void *state_vp) {                                   \
    bool *state = (bool *)state_vp;                                            \
    if (command == 'n') {                                                      \
      *state = true;                                                           \
    } else if (command == 'f') {                                               \
      *state = false;                                                          \
    }                                                                          \
  }
Declarations for ascii_serial_com_device and ascii_serial_com_register_pointers.
Declarations that should be outside of (and before) main() to ease use of ascii_serial_com_register_pointers with ascii_serial_com_device.
The only "public" variables are:
 bool streaming_is_on;
 circular_buffer_uint8 extraInputBuffer;
Notes
Don't follow this with a semicolon
Parameters
None
Definition at line 171 of file ascii_serial_com_register_pointers.h.
HANDLE_ASC_COMM_IN_POLLING_LOOP
#define HANDLE_ASC_COMM_IN_POLLING_LOOP (usart)
Value:
  if (!circular_buffer_is_empty_uint8(                                         \
          ascii_serial_com_device_get_output_buffer(&_ascd)) &&                \
      _serial_tx_buf_is_empty(usart)) {                                        \
    _tmp_byte = circular_buffer_pop_front_uint8(                               \
        ascii_serial_com_device_get_output_buffer(&_ascd));                    \
    usart_send(usart, _tmp_byte);                                              \
  }                                                                            \
  if (!circular_buffer_is_empty_uint8(&extraInputBuffer)) {                    \
    _ATOMIC {                                                                  \
      _tmp_byte = circular_buffer_pop_front_uint8(&extraInputBuffer);          \
    }                                                                          \
    circular_buffer_push_back_uint8(                                           \
        ascii_serial_com_device_get_input_buffer(&_ascd), _tmp_byte);          \
  }                                                                            \
  ascii_serial_com_device_receive(&_ascd)
Polling for ascii_serial_com_device and ascii_serial_com_register_pointers.
Within the polling loop, handles transmitting bytes, processing received bytes, and handling received messages. This is part of a group of macros to ease use of ascii_serial_com_register_pointers with ascii_serial_com_device.
Notes
Assumes that something else receives bytes and puts them in extraInputBuffer
Make sure this is inside a Try/Catch block
Follow this with a semicolon
Parameters
usart: the address of the USART used for transmitting bytes. For STM32: USART1, USART2, .... For AVR: UDR0, ....
Definition at line 285 of file ascii_serial_com_register_pointers.h.
READY_TO_STREAM_ASC_DEVICE_W_REGISTER_POINTERS
#define READY_TO_STREAM_ASC_DEVICE_W_REGISTER_POINTERS
Value:
  (streaming_is_on &&                                                          \
   circular_buffer_get_size_uint8(                                             \
       ascii_serial_com_device_get_output_buffer(&_ascd)) == 0)
Check if you should stream a message to the host.
This is a boolean value macro that checks if streaming is enabled and the transmit buffer is empty. If true, the user may stream a message to the host now with STREAM_TO_HOST_ASC_DEVICE_W_REGISTER_POINTERS
This is part of a group of macros to ease use of ascii_serial_com_register_pointers with ascii_serial_com_device.
Notes
Make sure this is inside a Try/Catch block
Definition at line 316 of file ascii_serial_com_register_pointers.h.
REGPRINTTYPEHEX
#define REGPRINTTYPEHEX PRIX8
Definition at line 84 of file ascii_serial_com_register_pointers.h.
REGPRINTTYPEINT
#define REGPRINTTYPEINT PRIu8
Definition at line 83 of file ascii_serial_com_register_pointers.h.
REGTYPE
#define REGTYPE uint8_t
Definition at line 82 of file ascii_serial_com_register_pointers.h.
REGWIDTHBITS
#define REGWIDTHBITS 8
Definition at line 80 of file ascii_serial_com_register_pointers.h.
REGWIDTHBYTES
#define REGWIDTHBYTES 1
Definition at line 81 of file ascii_serial_com_register_pointers.h.
SETUP_ASC_DEVICE_W_REGISTER_POINTERS
#define SETUP_ASC_DEVICE_W_REGISTER_POINTERS (register_map, register_write_masks, nRegs)
Value:
  ascii_serial_com_register_pointers_init(&_reg_pointers_state, register_map,  \
                                          register_write_masks, nRegs);        \
  ascii_serial_com_device_init(&_ascd, &_ascd_config);                         \
                                                                               \
  circular_buffer_init_uint8(&extraInputBuffer, _extraInputBuffer_size_,       \
                             _extraInputBuffer_raw)
Setup for ascii_serial_com_device and ascii_serial_com_register_pointers.
Setup that should be inside main() before the polling loop. This is part of a group of macros to ease use of ascii_serial_com_register_pointers with ascii_serial_com_device.
Notes
Make sure this is inside a Try/Catch block
Follow this with a semicolon
Parameters
register_map: the register map, type: REGTYPE * array
register_write_masks: the register write masks, type: REGTYPE array
nRegs: the length of the two arrays above
Definition at line 223 of file ascii_serial_com_register_pointers.h.
STREAM_TO_HOST_ASC_DEVICE_W_REGISTER_POINTERS
#define STREAM_TO_HOST_ASC_DEVICE_W_REGISTER_POINTERS (data, data_size)
Value:
  ascii_serial_com_device_put_s_message_in_output_buffer(&_ascd, '0', '0',     \
                                                         data, data_size)
Stream data to the host.
This macro puts a message in the output buffer
This is part of a group of macros to ease use of ascii_serial_com_register_pointers with ascii_serial_com_device.
Notes
Make sure this is inside a Try/Catch block
Parameters
data: a pointer to data or array of data to be sent
data_size: a uint describing the data size in bytes
Definition at line 339 of file ascii_serial_com_register_pointers.h.
Typedef Documentation
ascii_serial_com_register_pointers
typedef struct ascii_serial_com_register_pointers_struct ascii_serial_com_register_pointers
ASCII Serial Com Register Pointers State struct.
Keeps track of the state of the ASCII Serial Com Register Pointers
Function Documentation
ascii_serial_com_register_pointers_handle_message()
void ascii_serial_com_register_pointers_handle_message (ascii_serial_com * asc, char ascVersion, char appVersion, char command, char * data, size_t dataLen, void * register_pointers_state)
ASCII Serial Com Register Pointers handle message.
This is the function passed to ascii_serial_com_device as frw
The parameters are the same as in that function (and ascii_serial_com_get_message_from_input_buffer + register_pointers_state).
WILL CLOBBER data
Parameters
register_pointers_state should be a pointer to an initialized ascii_serial_com_register_pointers
Definition at line 26 of file ascii_serial_com_register_pointers.c.
References ascii_serial_com_put_error_in_output_buffer(), ascii_serial_com_put_message_in_output_buffer(), convert_hex_to_uint16(), ascii_serial_com_register_pointers_struct::n_regs, ascii_serial_com_register_pointers_struct::pointers, and ascii_serial_com_register_pointers_struct::write_masks.
ascii_serial_com_register_pointers_init()
void ascii_serial_com_register_pointers_init (ascii_serial_com_register_pointers * register_pointers_state, volatile REGTYPE ** pointers, REGTYPE * write_masks, uint16_t n_regs)
ASCII Serial Com Register Pointers init.
Initialize ASCII Serial Com register_pointers
Parameters
register_pointers_state should be an uninitialized ascii_serial_com_register_pointers object
pointers points to an array of pointers to registers (entries may be NULL). It's volatile so that it can point to device registers without reads/writes to them being optimized out.
an array of write masks. Every one bit in these masks is a bit that may be written to the registers.
n_regs is the number of registers in the pointers (not necessarily the number of bytes)
Definition at line 18 of file ascii_serial_com_register_pointers.c.
References ascii_serial_com_register_pointers_struct::n_regs, ascii_serial_com_register_pointers_struct::pointers, and ascii_serial_com_register_pointers_struct::write_masks.