
nativeobjs := native/ascii_serial_com_dummy_loopback_device.o native/ascii_serial_com_dummy_register_device.o native/ascii_serial_com_encode_decode_profiler.o
allobjs := $(allobjs) $(nativeobjs)
exes := $(exes) native/ascii_serial_com_dummy_loopback_device native/ascii_serial_com_dummy_register_device native/ascii_serial_com_encode_decode_profiler
