
nativeobjs := src/native/ascii_serial_com_dummy_loopback_device.o src/native/ascii_serial_com_dummy_register_device.o src/native/ascii_serial_com_encode_decode_profiler.o
allobjs := $(allobjs) $(nativeobjs)
exes := $(exes) src/native/ascii_serial_com_dummy_loopback_device src/native/ascii_serial_com_dummy_register_device src/native/ascii_serial_com_encode_decode_profiler
