name: C Workflow

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  c-build-unit-test-gcc:
    strategy:
      matrix:
        compiler-version: [9,10,11]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: ${{ matrix.compiler-version }}
        platform: x64
    - name: build
      run: |
        make install
      env:
        CC: gcc-${{ matrix.compiler-version }}
    - name: unit-test
      run: |
        testexes=$(ls build/*/test*)
        echo $testexes
        for i in $testexes; do echo $i; ./$i; done
      shell: bash

  c-build-unit-test-clang:
    strategy:
      matrix:
        compiler-version: [10,11,12,13]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: ${{ matrix.compiler-version }}
        platform: x64
    - name: build
      run: |
        make install
      env:
        CC: clang-${{ matrix.compiler-version }}
    - name: unit-test
      run: |
        testexes=$(ls build/*/test*)
        echo $testexes
        for i in $testexes; do echo $i; ./$i; done
      shell: bash

  c-clang-format:
    runs-on: ubuntu-latest
    needs: c-build-unit-test-clang
    steps:
    - uses: actions/checkout@v2
    - name: clang-format
      run: |
        clang-format -n -Werror *.c *.h native/*.c unit_test/*.c native/*.c avr/*.c avr/*.h
      shell: bash
